### PR TITLE
fix handleCardPayment types

### PR DESCRIPTION
**Pull request by dottodot**
Correcting handleCardPayment types to fix this issue https://github.com/richnologies/ngx-stripe/issues/72

### CODE REVIEW

**Comment by dottodot** [comment]
Don't merge yet still don't think it's correct.

**Comment by dottodot** [comment]
> Don't merge yet still don't think it's correct.

Ignore that it's fine.

**Comment by nickdnk** [comment]
Hey

Could you make argument b in handleCardPayment non-optional? The method always takes at least two arguments, so the second can never be null.

Also; add your change to `CHANGELOG.md` :)

**Comment by nickdnk** [comment]
Never mind my previous comment. I was wrong two times and then discarded it.

**Pull request merged**
