### PR TITLE
Fix Angular 8 peer dependency warning

### PR DESCRIPTION
**Pull request by dottodot**
**What are you adding/fixing?**

Not exactly critical but this will get rid of the peer dependency warning for Angular 8

**Have you added tests for your changes?**

N/A
**Will this need documentation changes?**

No
**Does this introduce a breaking change?**

No
**Other information**

### CODE REVIEW

**Comment by nickdnk** [comment]
I'm actually using this library with Angular 6, where it works fine (at least the parts I'm using). Is there a specific reason we cannot have>=6.0.0 in the peerDeps, @richnologies ?

**Comment by richnologies** [comment]
Hi @nickdnk not at all. I publish version range you suggest. Thanks again @dottodot

**Comment by nickdnk** [comment]
@richnologies Set the version to `>=6.0.0 <9.0.0` as we don't know if it will work with Angular 9 yet (I assume). Since we're not doing the `^6.0.0` syntax.

**Comment by richnologies** [comment]
@nickdnk done. Sorry for missing that

**Comment by nickdnk** [comment]
Cool. I think that'll be fine. Then when Angular 9 releases and you can verify it works there too (or fix whatever doesn't), you can just change 9.0.0 to 10.0.0 :)

**Pull request closed without merging**
